name: parser_ci
on:
  push:
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: 
          - "3.7"
    name: test-parsers
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install pip-21.3.1-py3-none-any.whl |
          python3 -m pip install clips-1.1.0-py3-none-any.whl |
          python3 -m pip install ddr_clips-1.1.9-py3-none-any.whl |
          python3 -m pip install ddr_python-1.0.9-py3-none-any.whl |
          python3 -m pip install ncclient-0.6.9-py2.py3-none-any.whl |
          python3 -m pip install pexpect-4.8.0-py2.py3-none-any.whl |
          python3 -m pip install ptyprocess-0.7.0-py2.py3-none-any.whl |
          python3 -m pip install xmltodict-0.13.0-py2.py3-none-any.whl |
          python3 -m pip install clipspy |
          python3 -m pip install regex |
          python3 -m pip install pyyaml |
          pip3 freeze

